# Generated by Django 4.0.2 on 2022-02-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_reporter_history_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Visit',
        ),
    ]
